"use client";

import { useMemo, useState } from "react";
import { syntheticLicenseRecommendations } from "@/lib/analytics/licenses";

type Decision = "pending" | "approved" | "rejected";

type LicenseRecommendation = (typeof syntheticLicenseRecommendations)[number];

export function LicenseOptimization({ recommendations = syntheticLicenseRecommendations }: { recommendations?: LicenseRecommendation[] }) {
  const [selectedProduct, setSelectedProduct] = useState(recommendations[0].product);
  const [decision, setDecision] = useState<Decision>("pending");
  const recommendation = useMemo(() => recommendations.find((item) => item.product === selectedProduct) ?? recommendations[0], [recommendations, selectedProduct]);
  function select(product: string) { setSelectedProduct(product); setDecision("pending"); }
  return <div className="optimization-shell">
    <header className="topbar"><a className="brand" href="/dashboard"><span className="brand-symbol" aria-hidden="true">A<span>↗</span></span><span>Enterprise IT <strong>AX</strong><small>OPERATIONS INTELLIGENCE</small></span></a><nav aria-label="Primary navigation"><a href="/investigate">Support Investigation</a><a href="/dashboard">Operations Dashboard</a><a className="nav-active" href="/optimization">License Optimization</a></nav><span className="demo-tag"><span className="dot" /> Synthetic environment</span></header>
    <main className="optimization-main">
      <div className="dashboard-heading"><div><div className="eyebrow">DECISION SUPPORT / LICENSE RENEWAL</div><h1>License Optimization<span className="version">v0.7</span></h1><p>Deterministic renewal quantity recommendations with an explicit human approval boundary.</p></div><div className="measurement"><span>DECISION MODE</span><strong>Recommendation only</strong><small>No contract or license change is executed.</small></div></div>
      <div className="license-layout"><aside className="license-list"><div className="panel-heading"><h2>License portfolio</h2><span className="count">{recommendations.length}</span></div><p className="small muted">Synthetic records · 90-day usage baseline</p>{recommendations.map((item) => <button key={item.product} className={item.product === recommendation.product ? "license-choice active" : "license-choice"} onClick={() => select(item.product)}><span>{item.product}</span><strong>{item.utilization}% utilization</strong><small>Renewal {item.renewalDate}</small></button>)}<div className="coverage-note"><span className="eyebrow">GOVERNANCE</span><p>Usage evidence supports a recommendation. Contract terms and final quantities remain human decisions.</p></div></aside>
        <section className="license-detail"><div className="recommendation-hero"><div><span className="eyebrow">RENEWAL RECOMMENDATION</span><h2>{recommendation.product}</h2><p>Renewal date: <strong>{recommendation.renewalDate}</strong> · {recommendation.daysUntilRenewal} days from synthetic measurement anchor</p></div><span className={`risk-tag risk-${recommendation.risk.toLowerCase()}`}>{recommendation.risk} risk</span></div>
          <div className="license-metric-grid"><div><span>Current seats</span><strong>{recommendation.currentSeats}</strong></div><div><span>90-day active users</span><strong>{recommendation.activeUsers90d}</strong></div><div><span>Utilization</span><strong>{recommendation.utilization}<small>%</small></strong></div><div><span>Annual cost</span><strong>{new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(recommendation.annualCost)}</strong></div></div>
          <section className="recommendation-result"><div><span className="eyebrow">PROPOSED RENEWAL QUANTITY</span><strong>{recommendation.recommendedSeats}<small> seats</small></strong><p>{recommendation.reduction} fewer than the current contract quantity.</p></div><div><span className="eyebrow">ESTIMATED ANNUAL SAVING</span><strong>{recommendation.estimatedAnnualSavingLabel}</strong><p>Potential gross saving before contract changes, fees, or operational costs.</p></div><div className="approval-boundary"><span aria-hidden="true">◇</span><div><strong>Human approval required</strong><p>The button below records a local demo review state only. It does not alter a contract or remove licenses.</p></div></div></section>
          <section className="license-section"><h2>Decision factors</h2><div className="factor-grid">{recommendation.factors.map((factor) => <article key={factor.label}><span>{factor.label}</span><strong>{factor.value}</strong><p>{factor.description}</p></article>)}</div></section>
          <section className="license-section calculation-section"><h2>Recommendation logic</h2><div className="calculation"><span>{recommendation.activeUsers90d} active</span><b>+</b><span>{recommendation.factors[1].value} reserved</span><b>+</b><span>{recommendation.factors[2].value} upcoming</span><b>+</b><span>{recommendation.factors[3].value} buffer</span><b>=</b><strong>{recommendation.calculation.unconstrainedRecommendation}</strong><i>then apply contract minimum {recommendation.calculation.contractMinimum} → {recommendation.recommendedSeats} seats</i></div><p className="small muted">Survey demand is included inside upcoming demand. Temporary inactive users are neither deleted nor added as a separate seat count.</p></section>
          <section className="license-section"><h2>Constraints & review notes</h2><ul className="constraint-list">{recommendation.constraints.map((constraint) => <li key={constraint}>{constraint}</li>)}</ul></section>
          <div className="decision-actions"><div><span className="eyebrow">DEMO REVIEW STATE</span><strong>{decision === "pending" ? "Awaiting human review" : decision === "approved" ? "Approved for external review" : "Rejected — no action taken"}</strong></div><div><button className="secondary-button" onClick={() => setDecision("rejected")}>Reject</button><button className="primary-button" onClick={() => setDecision("approved")}>Approve for review <span aria-hidden="true">↗</span></button></div></div>
          {decision !== "pending" && <p className="decision-notice" role="status">{decision === "approved" ? "Recorded locally as approved for external review. No contract or license operation was performed." : "Recorded locally as rejected. No contract or license operation was performed."}</p>}
        </section></div>
      <section className="data-method"><div><span className="eyebrow">DECISION BOUNDARY</span><h2>Recommendation is not execution</h2></div><div><p>The platform calculates only a potential renewal quantity and gross annual saving from synthetic inputs. An authorized person must validate contract constraints, temporary inactivity, demand assumptions, and vendor terms before any external action.</p><p>Risk labels are rule-based indicators for this demo, not legal, procurement, or financial advice.</p></div></section>
    </main><footer className="app-footer"><span>ENTERPRISE IT AX</span><p>All enterprise data is fully synthetic. No employer or confidential information is included.</p><span>Decision support · Human accountability</span></footer>
  </div>;
}
