begin;

-- v0.7's second synthetic slice uses generic departments and replaces all
-- synthetic rows on seed. This does not grant browser roles any access.
-- Existing rows belong only to the prior demo slice and are regenerated by
-- the seed scripts immediately after this migration.
delete from public.support_tickets where synthetic = true;

alter table public.support_tickets
  drop constraint support_tickets_department_check;

alter table public.support_tickets
  add constraint support_tickets_department_check
  check (department in ('Product', 'Operations', 'Customer Success', 'Finance', 'People', 'Commercial', 'IT Services'));

grant delete on public.support_tickets to service_role;
grant delete on public.licenses to service_role;

commit;
